services:
  backend:
    build: ./backend
    ports:
      - "8010:8010"
    volumes:
      - ./db-data:/app/data
    environment:
      - DB_PATH=/app/data/inventory.sqlite

  frontend:
    build: ./frontend-react
    ports:
      - "8080:80"
    depends_on:
      - backend
